runtime: python311

entrypoint: uvicorn api.main:app --host 0.0.0.0 --port 8080

# handlers:
# - url: /.*
#   script: auto

# endpoints_api_service:
#   # The following values are to be replaced by information from the output of
#   # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
#   name: https://projet7-api-credit-risk.appspot.com/
#   rollout_strategy: managed