channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.15.0
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - lightgbm==4.5.0
  - matplotlib==3.9.0
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==5.9.0
  - pyarrow==15.0.2
  - scikit-learn==1.5.0
  - scipy==1.14.0
name: mlflow-env
